# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpw 
      MARIADB_USER: user 
      MARIADB_PASSWORD: password 
      MARIADB_DATABASE: omeka
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306

  omeka:
    image: omeka-s    
    restart: always
    volumes:
      - ./config:/var/www/html/config
      - ./files:/var/www/html/files
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./logs:/var/www/html/logs
      - ./php.ini:/etc/php/7.4/apache2/php.ini
    ports:
      - 80:80
