# Use root/example as user/password credentials
version: '3.1'

networks:
  modpdsc_default:
    external: true

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpw 
      MARIADB_USER: user 
      MARIADB_PASSWORD: password 
      MARIADB_DATABASE: omeka
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - modpdsc_default

  omeka:
    image: omeka-s    
    restart: always
    volumes:
      - ./config:/var/www/html/config
      - ./files:/var/www/html/files
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./logs:/var/www/html/logs
      - ./php.ini:/etc/php/7.4/apache2/php.ini
    ports:
      - 80:80
    networks:
      - modpdsc_default
  
  minio:
      image: minio/minio:latest
      restart: always
      entrypoint: sh
      ports:
          - 10000:9000
          - 10001:10001
      environment:
          MINIO_ROOT_USER: "root"
          MINIO_ROOT_PASSWORD: "rootpass"
          MINIO_BROWSER_REDIRECT_URL:  http://localhost:10001
      entrypoint:
          bash -c 'mkdir -p /data/repository && /opt/bin/minio server /data --console-address ":10001"'
      volumes:
          - ./s3-data:/data
      healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:10001/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3
      networks:
        - modpdsc_default
